from pygame.locals import *

# Events constants
PLAYER_DEATH = USEREVENT + 1
DEATH_ANIMATION_DONE = USEREVENT + 2
MAP_FINISHED = USEREVENT + 3
COIN_COLLECTED = USEREVENT + 4
VIDEOMODE_CHANGED = USEREVENT + 5